---
title: "convert_tsv_to_dataframe"
author: "KiseokUChicago"
date: "2021-01-14"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

### Converting tsv files to dataframe
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=9, fig.height=9,
                      error=TRUE, echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE)
```


```{r}
# libraries
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)

# Make the desirable format
df <- read.csv(file='data/diel-Feb21/IPTL-CyanoSUMI-MI41M-18OMix-16O-B-T1-BDCL_filtered_PSMs.tsv', sep = '\t')
df <- tibble::rownames_to_column(df, var = 'Index')
df2 <- df %>% select(Index,Scan.Number, Base.Peptide.Sequence, log2.18O.16O.Ratio, Target., Decoy.)
df3 <- df2 %>% separate(Scan.Number, into = c('dir',"file_name"), sep = 'IPTL-')
colnames(df3)
df4 <- df3 %>% select(-dir)
colnames(df4)
df5 <- df4 %>% separate(file_name, sep=';', into= c('IPT','SpectrumID','ScanID'))
head(df5)
# remove unwanted substrings
df5$IPT <- str_remove(df5$IPT, '.raw')
df5$SpectrumID <- str_remove(df5$SpectrumID, ' SpectrumID: ')
df5$ScanID <- str_remove(df5$ScanID, ' scans: ') 
head(df5$ScanID) # watch out for the space in front
df6 <- df5 %>% separate(IPT,into=c('Cruise','Station','Isotope','16O','Replicate','Time','Depth'),sep='-') %>% select(-`16O`)
colnames(df6)
df7 <- df6 %>% unite(c('Depth','Time','Replicate','ScanID'),col=Spec_id, remove=F) 
df7 <- df7 %>% unite(c('Depth','Time','Replicate'),col=SampleID, remove=F) 
head(df7)
# Arrange column order
df8 <- df7 %>% select(Spec_id, Base.Peptide.Sequence, log2.18O.16O.Ratio,SampleID,Index,Cruise,Station,Isotope, Replicate, Time, Depth, SpectrumID, ScanID, Target., Decoy.)
head(df8)   
# screen and remove Decoy = True
df9 <- df8 %>% filter(Decoy.=='False')
# confirm
df9[df9$Decoy.=='True',]

# final form
head(df9)

```

### Doing it for all tsv files

```{r}
library(openxlsx)

# define function
convert_tsv <- function(file_number, filename){
  # Make the desirable format
  df <- read.csv(file=paste0(directory_path,"/" ,filename), sep = '\t')
  df <- tibble::rownames_to_column(df, var = 'Index')
  df2 <- df %>% select(Index,Scan.Number, Base.Peptide.Sequence, log2.18O.16O.Ratio, Target., Decoy.)
  df3 <- df2 %>% separate(Scan.Number, into = c('dir',"file_name"), sep = 'IPTL-')
  colnames(df3)
  df4 <- df3 %>% select(-dir)
  colnames(df4)
  df5 <- df4 %>% separate(file_name, sep=';', into= c('IPT','SpectrumID','ScanID'))
  head(df5)
  # remove unwanted substrings
  df5$IPT <- str_remove(df5$IPT, '.raw')
  df5$SpectrumID <- str_remove(df5$SpectrumID, ' SpectrumID: ')
  df5$ScanID <- str_remove(df5$ScanID, ' scans: ') 
  head(df5$ScanID) # watch out for the space in front
  df6 <- df5 %>% separate(IPT,into=c('Cruise','Station','Isotope','16O','Replicate','Time','Depth'),sep='-') %>% select(-`16O`)
  colnames(df6)
  df7 <- df6 %>% unite(c('Depth','Time','Replicate','ScanID'),col=Spec_id, remove=F) 
  df7 <- df7 %>% unite(c('Depth','Time','Replicate'),col=SampleID, remove=F) 
  head(df7)
  # Arrange column order
  df8 <- df7 %>% select(Spec_id, Base.Peptide.Sequence, log2.18O.16O.Ratio,SampleID,Index,Cruise,Station,Isotope, Replicate, Time, Depth, SpectrumID, ScanID, Target., Decoy.)
  # screen and remove Decoy = True
  df9 <- df8 %>% filter(Decoy.=='False')
  # confirm
  df9[df9$Decoy.=='True',]
  
  # final form
  head(df9)
  write.table(df9,file=paste0(file_number,'_',filename), sep='\t',row.names = F)
  openxlsx::write.xlsx(df9,paste0(file_number,'_',str_remove(filename,'.tsv'),'.xlsx'),rowNames=F)
}

# list all files in certain folder
directory_path = "data/diel-Feb21"
list_f <- list.files(path="data/diel-Feb21")
length(list_f)

# test example
convert_tsv('01','IPTL-CyanoSUMI-MI41M-18OMix-16O-B-T1-BDCL_filtered_PSMs.tsv')

# make file name starting from 01, 02, 
vec_00 <- sprintf("%02d", c(1:length(list_f)))
# loop through files and convert
for (i in c(1:length(list_f))){
  print(i)
  print(list_f[i])
  convert_tsv(vec_00[i], list_f[i])
}


```

### Aggregate all converted tsv files & make Peptide_id for all unique pep sequences

```{r}
#
tsv_files  <- list.files(pattern = '^[0-9].*_PSMs\\.tsv')
tables <- lapply(tsv_files, read.table, header = TRUE)
combined_tsv <- do.call(rbind , tables)
head(combined_tsv)
dim(combined_tsv)

# give unique peptide id's for all peptides
# give peptide name by frequency (peptide with greatest frequency gets Pep_1)
df_p <- transform(combined_tsv, freq= ave(seq(nrow(combined_tsv)), Base.Peptide.Sequence, FUN=length))
df_p[order(-df_p$freq), ] %>% head()
df_pepid <- df_p %>% select(Base.Peptide.Sequence,freq) %>% arrange(desc(freq)) %>% unique() %>% arrange()

# Distribution of frequency of each Peptide_id in all samples
theme_set(theme_bw())
his1 <- ggplot(df_pepid, aes(x=freq)) +
  geom_histogram(binwidth = 10) +
  scale_fill_brewer(palette='Set2') +
  ylab("Frequency \n") +
  xlab("\n Frequency of each unique peptide sequence") +
  ggtitle("Distribution of frequency of each Peptide_id in all samples \n")+
  ## adjust positions
  theme(plot.title = element_text(size = 20,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 15,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 15,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=10))
  # theme(panel.grid.major = element_blank())
  # theme(panel.grid.minor = element_blank())
his1

df_pepid2 <- tibble::rownames_to_column(df_pepid, var='rowid') 
df_pepid3 <- df_pepid2 %>% mutate(Peptide_id = paste0("Pep_",rowid)) %>% select(-rowid)
# check if sum of freq is same as all number of spectral reads
sum(df_pepid3$freq) == dim(combined_tsv)[1]
# write Peptide_id list
write.table(df_pepid3,"Peptide_id.tsv", sep='\t',row.names = F)

combined_tsv_pepid <- combined_tsv %>% left_join(df_pepid3, by=c('Base.Peptide.Sequence'='Base.Peptide.Sequence')) %>% select(-freq)

colnames(combined_tsv_pepid)
head(combined_tsv_pepid)
tail(combined_tsv_pepid)
# check whether there is no NA value in the dataframe
any(is.na.data.frame(combined_tsv_pepid))

write.table(combined_tsv_pepid,"Replicate_B_combined.tsv", sep='\t',row.names = F)
openxlsx::write.xlsx(combined_tsv_pepid,'Replicate_B_combined.xlsx',rowNames=F)


```




